---
branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - master
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: "+(feat|fix|perf|chore|ci|docs|refactor|test|style)/**"
    prerelease: "${name.split('/').slice(0, 2).join('-').toLowerCase()}"
    
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - 
    - "@semantic-release/github"
    - assets:
        - "dist/**"
