id: de.netzwerk-universitaetsmedizin.ebm-cpg
canonical: https://www.netzwerk-universitaetsmedizin.de/fhir/cpg-on-ebm-on-fhir
name: CPG-on-EBMonFHIR
title: Clinical Practice Guidelines (CPG) on EBMonFHIR
status: draft
version: 2.0.0
fhirVersion: 5.0.0
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: Universitätsmedizin Greifswald
  url: https://www.medizin.uni-greifswald.de/
dependencies:
  hl7.fhir.uv.cpg:
    version: 1.0.0
pages:
  index.md:
    title: Clinical Practice Guidelines (CPG) on EBMonFHIR
  profiles.md:
  codesystems.md:
    title: Code Systems
  valuesets.md:
    title: Value Sets
  extensions.md:
  examples.md:
  downloads.xml:
  history.md:
menu:
  Home: index.html
  Profiles: profiles.html
  Code Systems: codesystems.html
  Value Sets: valuesets.html
  Extensions: extensions.html
  Examples: examples.html
  Downloads: downloads.html
  History: history.html
parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  active-tables: 'true' # Whether to generate active tables in the generated fragments (tables that will expand and contract).
  apply-contact: 'false' # if true, overwrite all canonical resource contact details with that found in the IG.
  apply-jurisdiction: 'false' # if true, overwrite all canonical resource jurisdiction details with that found in the IG.
  apply-publisher: 'false' # if true, overwrite all canonical resource publisher details with that found in the IG.
  apply-version: 'false' # if true, overwrite all canonical resource version details with that found in the IG.  Default = false
  show-inherited-invariants: 'false' # If true, render inherited constraints in the full details and invariants view. Default = true
  usage-stats-opt-out: 'true' # If true, usage stats (information about extensions, value sets, and invariants being used) is not sent to fhir.org (see e.g. http://clinfhir.com/igAnalysis.html).
  excludexml: 'false' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludejsn: 'false' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludettl: 'true' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludemap: 'true' # when true, these parameters will cause the publisher to exclude the generation of the respective formats - xml, json or ttl  - and to exclude the respective tabs from the implementation guide pages.
  excludeexample: 'true'
  extension-domain: # An external domain from which extensions are allowed to come (else they'll be flagged as invalid when validating).
    - https://www.netzwerk-universitaetsmedizin.de
    - https://simplifier.net
