name: FHIR Validation

on:
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  fsh-fhir-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install fsh-sushi
        run: npm install && npm install -g fsh-sushi

      - name: Load validator
        run: curl -L https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -o ./validator_cli.jar

      - name: Install FHIR R5 CI
        run: ./download-fhir-r5-ci.sh

      - name: Execute validator
        run: fsh-validator --all
