name: ImplementationGuide Publisher

on:
  # Triggers the workflow on push or pull request events but only for the main or master branch
  push:
    branches:
      - main
      - master
      - staging
  pull_request:
    branches:
      - main
      - master
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-publisher:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@v3

      # read id, version and canonical from sushi-config.yaml
      - name: Run read-yaml action
        id: yaml-data
        uses: CumulusDS/get-yaml-paths-action@v1.0.1
        with:
          file: sushi-config.yaml
          version: version
          canonical: canonical
          id: id

      # display outputs from read-yaml action
      - name: Display read-yaml output
        run: |
          echo "id: ${{ steps.yaml-data.outputs.id }}"
          echo "target url: ${{ steps.yaml-data.outputs.canonical }}"
          echo "version: ${{ steps.yaml-data.outputs.version }}"

      # run ig publisher
      - name: Run the IG publisher
        uses: docker://hl7fhir/ig-publisher-base:latest
        with:
          args: ./run-ig-publisher.sh ${{ steps.yaml-data.outputs.canonical }} ${{ steps.yaml-data.outputs.version }}

      # deploy implementation guide to github pages
      - name: Deploy
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true

      # upload binaries to release
      - name: Upload binaries to release
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/package.tgz
          asset_name: ${{ steps.yaml-data.outputs.id }}-${{ steps.yaml-data.outputs.version }}.tgz
          tag: v${{ steps.yaml-data.outputs.version }}
          release_name: Release v${{ steps.yaml-data.outputs.version }}
          overwrite: true
